platform :ios, '12.0'

target 'iosApp' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for ios
pod 'Firebase/Core'
pod 'Fabric'
pod 'Crashlytics'
pod 'MaterialComponents'
end
